### PR TITLE
Added article: Data sovereignty revolution

### PR DESCRIPTION
**Pull request by leinue**
## Added article: Data sovereignty revolution

it's related to the issue #99 

----------------
<sub>
<i>

PreAngel Partners, 2011 - now <a href="https://pre-angel.com">PreAngel - PA</a>

</i>
</sub>

### CODE REVIEW

**Comment by leinue** [comment]
At present, this way of writing is too inefficient. What is the purpose of human invention of editor..

**Comment by leinue** [comment]
It's very time-consuming for me to write articles here every time. Is there any best practice?

**Comment by leinue** [comment]
image
I think image can be compressed automatically

**Comment by leinue** [comment]
image
I am VERY ANGRY, bullshit.I've wasted more than an hour on markdown lint.Why should we limit the specifications of pictures?

**Comment by leinue** [comment]
image
image
I do not know what the fucking limit size is, no image exceed 1MB.

**Comment by leinue** [comment]
> It is great to see your new article being posted here, and appreciate your patience to make it passed the linting rules, which is very important for making this repo maintainable and improve the reader's experience!

The platform should not restrict the size of pictures by force, but should be specified by the author's HTML.
Without CDN, the image access speed is very slow. I don't think it gives readers a good reading experience.

**Comment by huan** [comment]
We are currently working on the local CDN settings inside the China mainland.

**Pull request merged**
