### PR TITLE
#75 update avatar of xiangyu

### PR DESCRIPTION
**Pull request by Samurais**
## Please describe what your PR do

Related with #75 

Enhance avatar pic.

----------------
<sub>
<i>

PreAngel Partners, 2011 - now <a href="https://pre-angel.com">PreAngel - PA</a>

</i>
</sub>

### CODE REVIEW

**Comment by Samurais** [comment]
avatars are elegant now.

image

**Comment by huan** [comment]
It seems that you had deleted the avatar for Yu, and add another avatar file for Kai?

**Comment by huan** [comment]
image

Please check this commit and update the avatar of Yu before we can merge this PR.

**Comment by Samurais** [comment]
Yu's avatar is in the repo as latest version

https://github.com/Samurais/pre-angel.com/tree/master/docs/assets/peoples/yu-xiang

The diff message is about reducing size but not deleted.

**Comment by huan** [comment]
Merged.

Let's see the result after it had been published.

**Pull request merged**
